runtime custom-config/basics.vim
runtime custom-config/newline.vim

call plug#begin()
" don't support vim, only nvim
" Plug 'ThePrimeagen/vim-be-good'

" Plug 'tpope/vim-surround'
" Plug 'tpope/vim-repeat'

Plug 'machakann/vim-sandwich'

" AirLine
Plug 'vim-airline/vim-airline'

" File Manager
Plug 'preservim/nerdtree'
" quick comment
Plug 'preservim/nerdcommenter'
" Plug 'tpope/vim-commentary'

" navigate between vim and tmux smoothly, you can use the same command to
" navigate between window
Plug 'christoomey/vim-tmux-navigator'

" git
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'

call plug#end()

" \l 保存当前文件并 source 当前配置
" 方便 `~/.vimrc` 文件的编辑和调试
nnoremap <silent> <leader>l :w<CR>:source %<CR>

runtime custom-config/plugins/AirLine.vim
runtime custom-config/plugins/vim-gitgutter.vim
runtime custom-config/plugins/NERDTree.vim
runtime custom-config/plugins/NERDCommenter.vim
